#cloud-config
package_update: true
package_upgrade: true

groups:
  - docker

system_info:
  default_user:
    groups: [docker]

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - unattended-upgrades
  - git
  - zip

runcmd:
- curl -sL https://aka.ms/InstallAzureCLIDeb | bash
- az version > /tmp/az_version.txt
- mkdir -p /etc/apt/keyrings
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
- echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
- apt-get update
- apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
- systemctl enable docker
- systemctl start docker

# odaユーザーの作成とSSH鍵のコピー
- adduser --disabled-password --gecos "" oda
- usermod -aG sudo oda
- usermod -aG docker oda
- mkdir -p /home/oda/.ssh
- cp /home/azureadmin/.ssh/authorized_keys /home/oda/.ssh/
- chown -R oda:oda /home/oda/.ssh
- chmod 700 /home/oda/.ssh
- chmod 600 /home/oda/.ssh/authorized_keys

# GitHubリポジトリのクローン
- REPO_URL="https://github.com/Masahiro-wa/azure_container_Hands-on_with_Bicep.git"
- su - oda -c "git clone $REPO_URL /home/oda/workspace"

final_message: "The system is finally up, after $UPTIME seconds"
