subscription_id: ''
env_name: 'bicep-lab'
location: 'japaneast'

vnet_cidr: '10.0.0.0/16'
dev_subnet_cidr: '10.0.24.0/24'

UseSsh: 'True'
AdminPassword: ''
AdminUsername: 'azureadmin'
Admin_password: ''
SecurityType: "Standard"
OsDiskType: "Standard_LRS"
DevVmSize: "Standard_D2s_v3"
UbuntuOsVersion: "Ubuntu-2204"

DbName: 'backenddb'
DbRootName: 'dbadmin'

DockerFrontendImage: 'biceplabacre7cae610.azurecr.io/frontend:v1'
DockerBackendImage: 'biceplabacre7cae610.azurecr.io/backend:v1'
DockerSchedulerImage: 'biceplabacre7cae610.azurecr.io/schedule:v1'
